### ISSUE TITLE
Sierra Loadouts Menu nicht sortiert. 

### ISSUE THREAD

**Issue by Arywa** [German-Rangers-MM/GR_MM_Template_Zug_3_0#27]
### Beschreibung den Fehler

-

### Schritte zur Reproduktion des Fehlers

Sierra Sloten.
GRBase -> Loadouts - nicht sortiert.

### Erwartetes Verhalten

Sierra Sloten.
GRBase -> Loadouts - sortiert.

GrpFhr
Aufkl Sani
Scharfschütze
Spotter
NaSi

### Wenn du passende Screenshots oder Videos hast, füg sie hier bitte an. (Optional)

![image](https://github.com/user-attachments/assets/2c8ccb37-f66c-4999-9958-e68210ecc926)

### Fast fertig, wir wollen nur eben noch was sicherstellen.

- [X] Ich habe in Issues nachgesehen ob dieses Problem bereits gemeldet wurde oder es breits einen Pull-Request dazu gibt.
- [X] Ich würde gerne selbst an der Problemlösung mitarbeiten.

**Comment by ItsGiantCookie** [comment]
bearbeitet in #28
