### ISSUE TITLE
[ENHANCEMENT] Update Sierra Kisten

### ISSUE THREAD

**Issue by TheApacheLongbow** [German-Rangers-MM/GR_MM_Template_Zug_3_0#39]
### Was ist dein Vorschlag? 
Hängt der Vorschlag mit einem Problem zusammen? Wenn ja, beschreib es bitte.

Von Arya eingeschickte Überarbeitung der Sierra Kisten, neu Typ 1-5, Kiste 4 oder 5 muss leicht angepasst werden (nein, ihr bekommt keine 20 UAV Batts in einer Kiste)

### Beschreib eine mögliche Lösung.

Einfach mal fucking machen

### Noch ein paar Kleinigkeiten bevor du deinen Vorschlag abgeben kannst.

- [X] Ich habe in Issues nachgesehen ob diese Problem bereits gemeldet wurde oder es bereits einen Pull-Request dazu gibt.
- [X] Ich würde gerne selbst an der Problemlösung mitarbeiten.

**Comment by Arywa** [comment]
Je nachdem, ob wir die G17 bekommen, müssen weitere Kisten angepasst werden.

**Comment by ItsGiantCookie** [comment]
Erledigt in c25b06e6060ce371b39fd21fc24699d95e34b35b

Merged in #60
