### ISSUE TITLE
[ENHANCEMENT] 82mm Mortar Range Table

### ISSUE THREAD

**Issue by TheApacheLongbow** [German-Rangers-MM/GR_MM_Template_Zug_3_0#43]
### Was ist dein Vorschlag? 
Hängt der Vorschlag mit einem Problem zusammen? Wenn ja, beschreib es bitte.

Soll für alle relevanten Posten auf Wunsch von Sierra hinzugefügt werden weil sich die Tabelle, anders als bei der standard Arty Rangetable, mit einem Hotkey öffnen lässt

### Beschreib eine mögliche Lösung.

Brauche noch die Classname, dann kann implementiert werden

### Noch ein paar Kleinigkeiten bevor du deinen Vorschlag abgeben kannst.

- [X] Ich habe in Issues nachgesehen ob diese Problem bereits gemeldet wurde oder es bereits einen Pull-Request dazu gibt.
- [X] Ich würde gerne selbst an der Problemlösung mitarbeiten.

**Comment by Arywa** [comment]
ACE_RangeTable_82mm

**Comment by ItsGiantCookie** [comment]
Erledigt durch c25b06e6060ce371b39fd21fc24699d95e34b35b

**Comment by ItsGiantCookie** [comment]
Merged in #60
