### ISSUE TITLE
[ENHANCEMENT] NCD Kits für Sani

### ISSUE THREAD

**Issue by TheApacheLongbow** [German-Rangers-MM/GR_MM_Template_Zug_3_0#45]
### Was ist dein Vorschlag? 
Hängt der Vorschlag mit einem Problem zusammen? Wenn ja, beschreib es bitte.

Keine Ahnung, frag Cookie

### Beschreib eine mögliche Lösung.

Frag Cookie hab ich gesagt!

### Noch ein paar Kleinigkeiten bevor du deinen Vorschlag abgeben kannst.

- [X] Ich habe in Issues nachgesehen ob diese Problem bereits gemeldet wurde oder es bereits einen Pull-Request dazu gibt.
- [X] Ich würde gerne selbst an der Problemlösung mitarbeiten.

**Comment by ItsGiantCookie** [comment]
Added mit 12d722d77e4e084e8f3bacd4e9c7e83dd73e89a4
