### ISSUE TITLE
[ENHANCEMENT] Flashbang Kiste

### ISSUE THREAD

**Issue by TheApacheLongbow** [German-Rangers-MM/GR_MM_Template_Zug_3_0#49]
### Was ist dein Vorschlag? 
Hängt der Vorschlag mit einem Problem zusammen? Wenn ja, beschreib es bitte.

Eine Kiste mit Flashbangs damit diese einfacher ausgegeben werden können wenn angefragt/benötigt

### Beschreib eine mögliche Lösung.

Bro

### Noch ein paar Kleinigkeiten bevor du deinen Vorschlag abgeben kannst.

- [X] Ich habe in Issues nachgesehen ob diese Problem bereits gemeldet wurde oder es bereits einen Pull-Request dazu gibt.
- [X] Ich würde gerne selbst an der Problemlösung mitarbeiten.

**Comment by ItsGiantCookie** [comment]
Erledigt in Merge #60
