### ISSUE TITLE
[BUG] Steph & NCD

### ISSUE THREAD

**Issue by TheApacheLongbow** [German-Rangers-MM/GR_MM_Template_Zug_3_0#54]
### Beschreibung den Fehler

Die Dinger fehlen, stop asking me weird ass questions my guy

### Schritte zur Reproduktion des Fehlers

Ich gehe davon aus, dass du weist wie man das macht, also bekommst du stattdessen ein Zitat von Karl Marx aus meiner heutigen Soziologie Vorlesung: 
„Der in Arbeitskraft umgesetzte Teil des Kapitals [also des vorgeschossenen Geldes des
Kapitalisten] verändert dagegen seinen Wert im Produktionsprozeß. Er reproduziert sein
eigenes Äqzivalent und einen Überschuß darüber, Mehrwert, der selbst wechseln, größer
oder kleiner sein kann. Von einer konstanten Größe verwandelt sich dieser Teil des Kapitals
fortwährend in einen variablen. Ich nenne ihn daher (…): variables Kapital.“ (Marx, K. 1867, Das
Kapital, Bd. 1)

### Erwartetes Verhalten

Ich erwarte, dass du das verdammte Zitat liest du Lelleck

### Fast fertig, wir wollen nur eben noch was sicherstellen.

- [X] Ich habe in Issues nachgesehen ob dieses Problem bereits gemeldet wurde oder es bereits einen Pull-Request dazu gibt.
- [X] Ich würde gerne selbst an der Problemlösung mitarbeiten.

**Comment by ItsGiantCookie** [comment]
Added mit https://github.com/German-Rangers-MM/GR_MM_Template_Zug_3_0/commit/12d722d77e4e084e8f3bacd4e9c7e83dd73e89a4
