### ISSUE TITLE
[BUG] Rangefinder Mike LSan

### ISSUE THREAD

**Issue by TheApacheLongbow** [German-Rangers-MM/GR_MM_Template_Zug_3_0#56]
### Beschreibung den Fehler

Cookie be Rangefinderless

### Schritte zur Reproduktion des Fehlers

Frag Cookie

### Erwartetes Verhalten

Er wird es dir sagen

### Fast fertig, wir wollen nur eben noch was sicherstellen.

- [X] Ich habe in Issues nachgesehen ob dieses Problem bereits gemeldet wurde oder es bereits einen Pull-Request dazu gibt.
- [X] Ich würde gerne selbst an der Problemlösung mitarbeiten.

**Comment by ItsGiantCookie** [comment]
Fixed durch 5506ae411790c2ac3785726bee1f03661aadb1d6
