### ISSUE TITLE
[ENHANCEMENT] Lima Kiste Leichensäcke

### ISSUE THREAD

**Issue by TheApacheLongbow** [German-Rangers-MM/GR_MM_Template_Zug_3_0#57]
### Was ist dein Vorschlag? 
Hängt der Vorschlag mit einem Problem zusammen? Wenn ja, beschreib es bitte.

Bin Faul

### Beschreib eine mögliche Lösung.

Am besten nicht "Verbranntes Toast" nennen

### Noch ein paar Kleinigkeiten bevor du deinen Vorschlag abgeben kannst.

- [X] Ich habe in Issues nachgesehen ob diese Problem bereits gemeldet wurde oder es bereits einen Pull-Request dazu gibt.
- [X] Ich würde gerne selbst an der Problemlösung mitarbeiten.

**Comment by ItsGiantCookie** [comment]
Added durch 61637801b5a595a4f513cce594bfae2a6ae32525
