### ISSUE TITLE
[ENHANCEMENT] Pistolen

### ISSUE THREAD

**Issue by TheApacheLongbow** [German-Rangers-MM/GR_MM_Template_Zug_3_0#58]
### Was ist dein Vorschlag? 
Hängt der Vorschlag mit einem Problem zusammen? Wenn ja, beschreib es bitte.

add Flashlight
add Sight
add LLM

### Beschreib eine mögliche Lösung.

.

### Noch ein paar Kleinigkeiten bevor du deinen Vorschlag abgeben kannst.

- [X] Ich habe in Issues nachgesehen ob diese Problem bereits gemeldet wurde oder es bereits einen Pull-Request dazu gibt.
- [X] Ich würde gerne selbst an der Problemlösung mitarbeiten.

**Comment by ItsGiantCookie** [comment]
In arbeit durch #59
