### ISSUE TITLE
[ENHANCEMENT] Standardausrüstung

### ISSUE THREAD

**Issue by TheApacheLongbow** [German-Rangers-MM/GR_MM_Template_Zug_3_0#59]
### Was ist dein Vorschlag? 
Hängt der Vorschlag mit einem Problem zusammen? Wenn ja, beschreib es bitte.

Ausrüstung die für alle verfügbar sein soll zieht in ein extra Dokument um damit die einzelnen Packlisten für die Spots zu entschlacken und Maintenance zu verbessern: In den Packlisten ist nur noch drin was den spezifischen Slot besonders macht

### Beschreib eine mögliche Lösung.

.

### Noch ein paar Kleinigkeiten bevor du deinen Vorschlag abgeben kannst.

- [X] Ich habe in Issues nachgesehen ob diese Problem bereits gemeldet wurde oder es bereits einen Pull-Request dazu gibt.
- [X] Ich würde gerne selbst an der Problemlösung mitarbeiten.

**Comment by ItsGiantCookie** [comment]
In arbeit 54457f3be2a493198c1b1f159595ee257886af74
